const mockResponse = {
  status: "success",
  totalResults: 15016,
  results: [
    {
      article_id: "a20c14a7ff6c14a50848eb3c059dda95",
      title: "Yüksekova’da lapa lapa kar yağışı",
      link: "https://www.yenicaggazetesi.com.tr/yuksekovada-lapa-lapa-kar-yagisi-772975h.htm",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "Hakkari Yüksekova’da akşam saatlerinde başlayan kar yağışı ilçeyi beyaza bürüdü.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:44:45",
      image_url: "https://cdn.yenicaggazetesi.com.tr/news/1136449.jpg",
      source_id: "yenicaggazetesi",
      source_url: "http://www.yenicaggazetesi.com.tr",
      source_icon: "https://i.bytvi.com/domain_icons/yenicaggazetesi.png",
      source_priority: 123344,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "5128cca4b0c15d4b31bfe7e44e2bb509",
      title: "CIA Direktörü Burns, Orta Doğu'ya gitti",
      link: "https://www.haber16.com/cia-direktoru-burns-orta-dogu-ya-gitti/1406052/",
      keywords: null,
      creator: null,
      video_url: null,
      description: null,
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:39:00",
      image_url:
        "https://www.haber16.com/images/genel/detayfoto_1.jpg?v=2023040500200720230613030833",
      source_id: "haber16",
      source_url: "https://www.haber16.com",
      source_icon: "https://i.bytvi.com/domain_icons/haber16.png",
      source_priority: 6562448,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "0245fc5d6f0099235e2516091f88c3fe",
      title:
        'BM\'den çarpıcı Gazze açıklaması! "Geceleri uykumuzu kaçırıyor olması lazım"',
      link: "https://www.star.com.tr/dunya/bmden-carpici-gazze-aciklamasi-geceleri-uykumuzu-kaciriyor-olmasi-lazim-haber-1855172/",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "İsrail 7 Ekim'den bu yana Gazze'de sayısız katliam gerçekleştirmeyi sürdürürken, Birleşmiş Milletlerden (BM) dikkat çekici bir açıklama geldi. BM yetkilisi Martin Griffiths X sosyal medya hesabı üzerinden yaptığı paylaşımda, \"Gazze'deki durumun geceleri uykumuzu kaçırıyor olması lazım\" mesajını yayımladı.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:37:55",
      image_url:
        "https://imgs.star.com.tr/imgsdisk/2024/03/08/bmden-carpici-gazze-acikl-685.jpg",
      source_id: "star_tr",
      source_url: "https://star.com.tr",
      source_icon: "https://i.bytvi.com/domain_icons/star_tr.png",
      source_priority: 430241,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "d84fe5288ec36d0429cdaa1d928f10a5",
      title: "Caner Erkin'e 7 maç ceza",
      link: "https://www.odatv.com/spor/caner-erkine-7-mac-ceza-120032173",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "Eyüpsporlu Caner Erkin, hakeme ve temsilciye yönelik hakaretleri nedeniyle 7 maç men cezası aldı.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:37:36",
      image_url:
        "https://img.odatv.com/rcman/Cw1280h720q95gc/storage/files/images/2024/03/08/caner-erkine-7-mac-ceza-w7i7.jpg",
      source_id: "odatv4",
      source_url: "https://www.odatv4.com",
      source_icon: "https://i.bytvi.com/domain_icons/odatv4.png",
      source_priority: 168972,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "c75e441670df731df82010f1d0c8ee0f",
      title: "İlk Arap ve başörtülü kadın astronot uzay yolculuğuna hazır",
      link: "https://www.karar.com/dunya-haberleri/ilk-arap-ve-basortulu-kadin-astronot-uzay-yolculuguna-hazir-1844685",
      keywords: null,
      creator: null,
      video_url: null,
      description:
        "Nura El Matruşi, çocukluk hayalini gerçekleştirerek bu hafta ABD Ulusal Havacılık ve Uzay Dairesi’nin (NASA) astronot eğitim programından mezun olan ilk Arap kadın oldu. Birleşik Arap Emirlikleri’nden 30 yaşındaki El Matruşi, artık uzaya doğru yola çıkmaya hazır.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:33:00",
      image_url: "https://cdn.karar.com/news/1672791.jpg",
      source_id: "karar",
      source_url: "https://www.karar.com",
      source_icon: "https://i.bytvi.com/domain_icons/karar.png",
      source_priority: 332816,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "48cb3be6e029df9dd2ccd49c3fd9db7d",
      title: "Aydın'da feci kaza! Trenin altında kalan kişi hayatını kaybetti",
      link: "https://www.tgrthaber.com.tr/gundem/aydinda-feci-kaza-trenin-altinda-kalan-kisi-hayatini-2936878",
      keywords: ["gündem"],
      creator: null,
      video_url: null,
      description:
        "Aydın'ın İncirliova bölgesinde, yolcu treninin çarptığı bir kişi hayatını kaybetti.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:32:44",
      image_url:
        "https://i.tgrthaber.com.tr/images/haberler/24-03/08/aydinda-feci-kaza-trenin-altinda-kalan-kisi-hayatini-kaybetti-17098543842402.jpg",
      source_id: "tgrthaber",
      source_url: "https://www.tgrthaber.com.tr",
      source_icon: null,
      source_priority: 662863,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "15bb42fc4ac8a11251011547e9d90a43",
      title:
        "CFPB, 8 dolarlık kredi kartı gecikme ücreti sınırı nedeniyle dava ile karşı karşıya",
      link: "https://tr.investing.com/news/economy/cfpb-8-dolarlk-kredi-kart-gecikme-ucreti-snr-nedeniyle-dava-ile-kars-karsya-93CH-2735938",
      keywords: null,
      creator: ["Investing.com"],
      video_url: null,
      description: null,
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:31:24",
      image_url:
        "https://i-invdn-com.investing.com/news/general-use-news-image3_M_1440049476.jpg",
      source_id: "investing_tr",
      source_url: "https://tr.investing.com",
      source_icon: null,
      source_priority: 1205,
      country: ["turkey"],
      category: ["business"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "175a136ad473801ad2e4396297231ef6",
      title:
        "Guiyang And Gui'an Strive To Build Internationally-Competitive Smart Computing Base",
      link: "https://menafn.com/1107951360/Guiyang-And-Guian-Strive-To-Build-Internationally-Competitive-Smart-Computing-Base",
      keywords: null,
      creator: ["marketing@menafn.com (MENAFN)"],
      video_url: null,
      description:
        "(MENAFN - PR Newswire) BEIJING, March 7, 2024 /PRNewswire/ -- A news report from com:\"Guiyang City and Gui'an New Area in Southwest China's Guizhou province are making every effort to build an ...",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:30:55",
      image_url: "https://menafn.com/images/Menafn_SmallLogo.jpg",
      source_id: "menafn",
      source_url: "https://menafn.com",
      source_icon: "https://i.bytvi.com/domain_icons/menafn.png",
      source_priority: 1117534,
      country: [
        "georgia",
        "united arab emirates",
        "singapore",
        "mongolia",
        "brunei",
        "armenia",
        "bhutan",
        "yemen",
        "sri lanka",
        "macau",
        "turkmenistan",
        "myanmar",
        "qatar",
        "laos",
        "north korea",
        "kazakhstan",
        "kuwait",
        "bangladesh",
        "malaysia",
        "israel",
        "pakistan",
        "turkey",
        "philippines",
        "azerbaijan",
        "tajikistan",
        "cyprus",
        "timor-leste",
        "japan",
        "bahrain",
        "kyrgyzstan",
        "thailand",
        "syria",
        "indonesia",
        "saudi arabia",
        "nepal",
        "vietnam",
        "lebanon",
        "maldives",
        "south korea",
        "india",
        "jordan",
        "iraq",
        "uzbekistan",
        "taiwan",
        "china",
        "iran",
        "afghanistan",
        "cambodia",
      ],
      category: ["top"],
      language: "english",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "7fa1e73a872fde14f4be56d18b91ef49",
      title:
        "Yazar Eylem Tok’un katil oğlunun çarptığı genç: Yardım istemek için çıkarttım telefonumu elimden aldılar",
      link: "https://tele1.com.tr/yazar-eylem-tokun-katil-oglunun-carptigi-genc-yardim-istemek-icin-cikarttim-telefonumu-elimden-aldilar-1022809/",
      keywords: ["haber", "eylem tok", "i̇brahim gümüş"],
      creator: ["Barış Önal"],
      video_url: null,
      description:
        "Yazar Eylem Tok’un 17 yaşındaki oğlu Timur Cihantimur’un aracıyla çarptığı ATV’de bulunan ve kazadan yaralı kurtulan İbrahim Gümüş olay anını anlattı. Gümüş, telefonunun kayıp olduğunu söyleyerek, “Yardım istemek için çıkarttım biri elimden aldı” dedi. Katil Cihantimur, annesi Eylem Tok tarafından kazanın ardından yurtdışına kaçırılmış ve iki isim içinde kırmızı bülten talep edilmişti. Sabah’ta yer alan […]",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:30:12",
      image_url: "https://tele1.com.tr/wp-content/uploads/2024/03/KATILL.jpg",
      source_id: "tele1",
      source_url: "https://tele1.com.tr",
      source_icon: "https://i.bytvi.com/domain_icons/tele1.png",
      source_priority: 374574,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
    {
      article_id: "e53efe59fe695e6c065297400e76f579",
      title: "Demokrat Parti Genel Başkan Yardımcısı İstifa Etti",
      link: "https://www.haber7.com/guncel/haber/3397072-demokrat-parti-genel-baskan-yardimcisi-istifa-etti",
      keywords: ["güncel"],
      creator: null,
      video_url: null,
      description:
        "Demokrat Parti Genel Başkan Yardımcısı İlay Aksoy, görevinden istifa ettiğini duyurdu.",
      content: "ONLY AVAILABLE IN PAID PLANS",
      pubDate: "2024-03-07 23:30:00",
      image_url:
        "https://i20.haber7.net/resize/1280x720//haber/haber7/photos/2024/10/demokrat_parti_genel_baskan_yardimcisi_istifa_etti_1709854173_1023.jpeg",
      source_id: "haber7",
      source_url: "https://www.haber7.com",
      source_icon: "https://i.bytvi.com/domain_icons/haber7.png",
      source_priority: 161356,
      country: ["turkey"],
      category: ["top"],
      language: "turkish",
      ai_tag: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      sentiment_stats: "ONLY AVAILABLE IN PROFESSIONAL AND CORPORATE PLANS",
      ai_region: "ONLY AVAILABLE IN CORPORATE PLANS",
    },
  ],
  nextPage: "1709854200147048718",
};

export async function fetchNews() {
  //   const resp = await fetch(
  //         "https://newsdata.io/api/1/news?country=tr&apikey=pub_39398456c4ae1777ca05a2a6dc24fd9e30280"
  //     );
  //     if (!resp.ok) {
  //         throw new Error("Network response was not ok");
  //     }
  //     return await resp.json();
  return mockResponse;
}
